# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentdeck" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "5ee7df01d87b04aa95308b0b0f798d71f7056c383521b5861360807d2b80cfe2"
      url "https://github.com/visualabsai/agentdeck/releases/download/v#{version}/agentdeck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/visualabsai/agentdeck"
    end
    on_intel do
      sha256 "eec6ac12ecf47985475f2542645ad79cf1cce81b13427fa3a55a029e5497a27e"
      url "https://github.com/visualabsai/agentdeck/releases/download/v#{version}/agentdeck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/visualabsai/agentdeck"
    end
  end
  on_linux do
    on_arm do
      sha256 "bc748d65662218e7387764aba368470f7f6cf1160ac3b178a8a88eb787665285"
      url "https://github.com/visualabsai/agentdeck/releases/download/v#{version}/agentdeck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/visualabsai/agentdeck"
    end
    on_intel do
      sha256 "02b01b2971666f94d420cccd9703d3dfcf2303dbd482c804cec829517cb717ab"
      url "https://github.com/visualabsai/agentdeck/releases/download/v#{version}/agentdeck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/visualabsai/agentdeck"
    end
  end

  name "agentdeck"
  desc "One dashboard for every CLI coding agent on your machine"
  homepage "https://github.com/visualabsai/agentdeck"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agentdeck"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentdeck"]
    end
  end

  # No zap stanza required
end
